# Imports

In [15]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
# For Kaggle
# for dirname, _, filenames in os.walk('../input/'):
for dirname, _, filenames in os.walk('./input/'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        path = os.path.join(dirname, filename)
data = pd.read_csv(path)
data.head()


# Any results you write to the current directory are saved as output.

./input/telco-customer-churn.zip
./input/WA_Fn-UseC_-Telco-Customer-Churn.csv

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [16]:
x = data.iloc[:,1:20]
x.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65

# Preprocessing

In [17]:
y = data.iloc[:,20:]
yy = data.select_dtypes(include=[object])
type(y.head())
# y = y.replace({'Churn':{'Yes':True, 'No':False}})
y.Churn.unique()

array(['No', 'Yes'], dtype=object)

In [19]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

y = y.apply(le.fit_transform)
y.Churn.unique()

array([0, 1], dtype=int64)

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.20)
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

for col in X_test.columns.values:
    print("Before : ",X_train[col].unique())
    if X_test[col].dtypes == 'object':
        d = X_train[col].append(X_test[col])
        le.fit(d.values)
        X_train[col] = le.transform(X_train[col])
        X_test[col] = le.transform(X_test[col])
        print("After : ", X_train[col].unique())
X_train.head()

Before :  ['Male' 'Female']
After :  [1 0]
Before :  [1 0]
Before :  ['Yes' 'No']

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

After :  [1 0]
Before :  ['No' 'Yes']
After :  [0 1]
Before :  [69  6 59 46 34 61 53  5 71 40 67 43 36 12  1  8 13 23 62 17 72 31 24 51
 58 41 55 18 20 25 44 27 10  3  2 66 63  4 29 45 52 48 32 16  7 35 56  9
 68 14 47 11 65 26 22 64 15 37 19 33 60 39 28 70 42 49 50 30 54 21  0 38
 57]
Before :  ['Yes' 'No']
After :  [1 0]
Before :  ['Yes' 'No' 'No phone service']
After :  [2 0 1]
Before :  ['Fiber optic' 'No' 'DSL']
After :  [1 2 0]
Before :  ['Yes' 'No internet service' 'No']
After :  [2 1 0]
Before :  ['No' 'No internet service' 'Yes']
After :  [0 1 2]
Before :  ['Yes' 'No internet service' 'No']
After :  [2 1 0]
Before :  ['Yes' 'No internet service' 'No']
After :  [2 1 0]
Before :  ['Yes' 'No internet service' 'No']
After :  [2 1 0]
Before :  ['Yes' 'No internet service' 'No']
After :  [2 1 0]
Before :  ['One year' 'Month-to-month' 'Two year']
After :  [1 0 2]
Before :  ['Yes' 'No']
After :  [1 0]
Before :  ['Mailed check' 'Electronic check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
After :  [3 2 0 1]
Before :  [110.55  20.2   94.05 ... 105.9   76.9   66.5 ]
Before :  ['7610.1' '98.35' '5483.9' ... '637.4' '6293.75' '2431.35']
After :  [5831 6500 4550 ... 5136 5086 2079]

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
6255,1,1,1,0,69,1,2,1,2,0,2,2,2,2,1,1,3,110.55,5831
1141,1,0,0,1,6,1,0,2,1,1,1,1,1,1,0,1,3,20.20,6500
2166,0,1,1,0,59,1,2,1,2,2,2,2,0,0,1,1,2,94.05,4550
3042,1,0,0,0,46,0,1,0,0,2,0,0,0,0,0,0,0,30.30,688
397,0,0,0,0,34,1,0,1,0,2,0,0,0,0,0,1,1,73.95,2181

In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# Multi-Layer Perceptron
## Artificial Neural Network

In [23]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(10,2,20), max_iter = 1000)
mlp.fit(X_train, y_train.values.ravel())

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(10, 2, 20), learning_rate='constant',
              learning_rate_init=0.001, max_iter=1000, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [24]:
predictions = mlp.predict(X_test)

# Accuracy

In [25]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test,predictions))
accuracy = accuracy_score(y_test, predictions)
print("Accuracy : ", accuracy)

[[927 100]
 [214 168]]
              precision    recall  f1-score   support

           0       0.81      0.90      0.86      1027
           1       0.63      0.44      0.52       382

    accuracy                           0.78      1409
   macro avg       0.72      0.67      0.69      1409
weighted avg       0.76      0.78      0.76      1409

Accuracy :  0.7771469127040455

# References

[introduction-to-neural-networks-with-scikit-learn](http://https://stackabuse.com/introduction-to-neural-networks-with-scikit-learn/)

[practical-guide-data-preprocessing-python-scikit-learn](https://www.analyticsvidhya.com/blog/2016/07/practical-guide-data-preprocessing-python-scikit-learn/)